### 首页
GET http://{{host}}
Content-Type: application/json

### 首页HTML
GET http://{{host}}
Content-Type: text/html

### 预览
GET http://{{host}}/wisdom?preview=1
Accept: application/json

### 随机展示
GET http://{{host}}/wisdom
Accept: text/html

### POST 首页
POST http://{{host}}/api/wisdom
Content-Type: application/json

{
    "Sentence": "hello4"
}


