### 默认wisdom随机展示
GET http://{{host}}/wisdom
Accept: text/html

### 预览
GET http://{{host}}/wisdom?preview=1
Accept: application/json

### json响应
GET http://{{host}}/api/wisdom
Accept: application/json

### 首页
GET http://{{host}}
Content-Type: application/json

### POST 首页
POST http://{{host}}?startTime=20240101&type=custom
Content-Type: application/json

{
    "user": {
        "id": 100,
        "like": "coding"
    },
    "age": 36
}

