### 默认wisdom随机展示
GET http://{{host}}/wisdom
Accept: text/html

### 预览
GET http://{{host}}/wisdom?preview=1
Accept: application/json

### json响应
GET http://{{host}}/api/wisdom
Accept: application/json

###
# 首页
GET http://{{host}}
Accept: application/json

###


